#!/bin/bash

CLIENT_CACHE_DIR=client_cache
SERVER_CACHE_DIR=server_cache

function killall() {
  killserver
  killclient
}

function killclient() {
  fusermount -u ${CLIENT_CACHE_DIR} > /dev/null 2>&1
  pkill nfsmount > /dev/null
}

function killserver() {
  pkill runserver > /dev/null
}

# Note: this must be called only once, otherwise mkdir call will block FUSE when server tying to restart. 
# mkdir -p ${CLIENT_CACHE_DIR} ${SERVER_CACHE_DIR}

if [ "$1" = "server" ]; then
  killserver
  ./runserver ${SERVER_CACHE_DIR}

elif [ "$1" = "client" ]; then
  shift
  killclient
  ./nfsmount ${CLIENT_CACHE_DIR} -f $@
fi
